which_project: &which_project beefcattle
env: &env
  run: QA
  updateActionAPI: DEV_API
  version: 2.3.1
  RUN_LEVEL: 3
  dataBaseURI:
  projectName: *which_project
  loginhosts:
    DEV:
      PASSPORT:
    QA:
      PASSPORT:

flowerChaser:
  <<: *env
  database:
    DEV:
      host_ip:
    QA:
      host_ip:
  urldict:

  accounttype: 'user'
  hosts:
    DEV:
    DEV_API:
    QA:
    QA_API: