which_project: &which_project middleground
env: &env
  run: DEV
  updateActionAPI: DEV_API
  version: 2.3.1
  RUN_LEVEL: 5
  dataBaseURI: 5595ec6c66c0374940fb2d6919a487f9b500f8602951206c6f9b85cab245bd1e90a2c42c9b0fb3883c44aadb5235b9dc94d8411f761298d477315e878eb9a87f
  projectName: *which_project

flowerChaser:
  <<: *env
  database:
    DEV:
      host_ip: 00cd6c8916486ff3b8c4180bbe5902f8
    QA:
      host_ip: 38decc2956f8bcf5731227852dd4d5bd
  urldict:
    FC_PASSPORT: "Passport"
    FC_USER: "User"
    FC_BEE: "Bee"
    FC_TRADE: "Trade"
  accounttype: 'user'
  hosts:
    DEV:
      FC_BEE: 'http://dev-gateway.worldfarm.com/fc-bee'
      FC_PASSPORT: 'http://dev-gateway.worldfarm.com/world-passport'
      FC_USER: 'http://dev-gateway.worldfarm.com/world-user'

    DEV_API:
      FC_BEE: 'http://dev-gateway.worldfarm.com/fc-bee'
      FC_PASSPORT: 'http://dev-passport.worldfarm.com'
      FC_USER: 'http://dev-user.worldfarm.com'

    QA:
      FC_BEE: 'http://qa-gateway.worldfarm.com/fc-bee'
      FC_PASSPORT: 'http://qa-gateway.worldfarm.com/world-passport'
      FC_TRADE: 'http://qa-gateway.worldfarm.com/fc-trade'
      FC_USER: 'http://qa-gateway.worldfarm.com/world-user'

    QA_API:
      FC_BEE: 'http://qa-gateway.worldfarm.com/fc-bee'
      FC_TRADE: 'http://qa-gateway.worldfarm.com/fc-trade'
      FC_PASSPORT: 'http://qa-gateway.worldfarm.com/world-passport'
      FC_USER: 'http://qa-gateway.worldfarm.com/world-user'

worldFarm:
  <<: *env
  database:
    DEV:
      host_ip: 00cd6c8916486ff3b8c4180bbe5902f8
    QA:
      host_ip: 0e1570fb7aa32f677daffb5047982dbb
  urldict:
    WF_OFFLINE: "Offline"
    WF_USER: "User"
    WF_KOALA: "Koala"
    WF_PASSPORT: "Passport"
  accounttype: 'wf_account'
  account:
    username: 632948101@qq.com
    password: 1234567
  hosts:
    DEV:
      WF_OFFLINE: 'http://dev-gateway.worldfarm.com/world-offline'
      WF_USER: 'http://dev-gateway.worldfarm.com/world-user'
      WF_KOALA: 'http://dev-gateway.worldfarm.com/world-koala'
      WF_PASSPORT: 'http://dev-gateway.worldfarm.com/world-passport'
      WF_SSO: 'http://dev.sso.worldfarm.com'
      WF_MGR: 'http://dev-mgr.agrrobot.com'

    DEV_API:
      WF_OFFLINE: 'http://dev-offline.worldfarm.com'
      WF_USER: 'http://dev-user.worldfarm.com'
      WF_KOALA: 'http://dev-koala.worldfarm.com'
      WF_PASSPORT: 'http://dev-passport.worldfarm.com'

    QA:
      WF_OFFLINE: 'http://qa-gateway.worldfarm.com/world-offline'
      WF_USER: 'http://qa-gateway.worldfarm.com/world-user'
      WF_KOALA: 'http://qa-gateway.worldfarm.com/world-koala'
      WF_PASSPORT: 'http://qa-gateway.worldfarm.com/world-passport'

    QA_API:
      WF_USER: 'http://qa-user.worldfarm.com'
      WF_KOALA: 'http://qa-koala.worldfarm.com'
      WF_PASSPORT: 'http://qa-passport.worldfarm.com'
      WF_OFFLINE: 'http://qa-offline.worldfarm.com'
      WF_SSO: 'http://qa.sso.worldfarm.com'

middleground:
  <<: *env
  database:
    DEV:
      host_ip: 00cd6c8916486ff3b8c4180bbe5902f8
    QA:
      host_ip: 38decc2956f8bcf5731227852dd4d5bd
  urldict:
    MP_PASSPORT: "Passport"
    MP_PRODUCT: "Product"
  accounttype: 'user'
  hosts:
    DEV:
      MP_PRODUCT: 'http://dev-gateway.worldfarm.com/mp-product'
      FC_PASSPORT: 'http://dev-gateway.worldfarm.com/world-passport'

    DEV_API:
      MP_PRODUCT: 'http://dev-gateway.worldfarm.com/mp-product'
      MP_PASSPORT: 'http://dev-gateway.worldfarm.com/world-passport'

    QA:
      MP_PRODUCT: 'http://qa-gateway.worldfarm.com/fc-bee'
      MP_PASSPORT: 'http://qa-gateway.worldfarm.com/world-passport'

    QA_API:
      MP_PRODUCT: 'http://qa-gateway.worldfarm.com/fc-bee'
      MP_PASSPORT: 'http://qa-gateway.worldfarm.com/world-passport'

wxshop:
  <<: *env
  database:
    DEV:
      host_ip: 00cd6c8916486ff3b8c4180bbe5902f8
    QA:
      host_ip: 38decc2956f8bcf5731227852dd4d5bd
  urldict:
    WX_PASSPORT: "Passport"
    WX_PRODUCT: "Product"
    WX_MALL: "Mall"
  accounttype: 'user'
  hosts:
    DEV:
      WX_PRODUCT: 'http://dev-gateway.worldfarm.com/wx-product'
      WX_PASSPORT: 'http://dev-gateway.worldfarm.com/world-passport'
      WX_MALL: 'http://dev-gateway.worldfarm.com/wx-mall'

    DEV_API:
      WX_PRODUCT: 'http://dev-gateway.worldfarm.com/wx-product'
      WX_PASSPORT: 'http://dev-gateway.worldfarm.com/world-passport'
      WX_MALL: 'http://dev-gateway.worldfarm.com/wx-mall'

    QA:
      WX_PRODUCT: 'http://qa-gateway.worldfarm.com/wx-product'
      WX_PASSPORT: 'http://qa-gateway.worldfarm.com/world-passport'
      WX_MALL: 'http://qa-gateway.worldfarm.com/wx-mall'

    QA_API:
      WX_PRODUCT: 'http://qa-gateway.worldfarm.com/wx-product'
      WX_PASSPORT: 'http://qa-gateway.worldfarm.com/world-passport'
      WX_MALL: 'http://qa-gateway.worldfarm.com/wx-mall'